INSERT INTO `banks` (`code`, `name`, `year`, `type`, `category`, `status`, `ownership`) VALUES
('116', 'Bank Aceh Syariah', 1957, 'Syariah', 'BPD', 'Nondevisa', 'Pemerintah daerah di Aceh'),
('947', 'Bank Aladin Syariah', 1994, 'Syariah', 'Swasta (lokal)', 'Devisa', 'Aladin Global Ventures'),
('567', 'Bank Allo Indonesia', 1992, 'Konvensional', 'Swasta (lokal)', 'Nondevisa', 'Mega Corpora'),
('531', 'Bank Amar Indonesia', 1991, 'Konvensional', 'Swasta (asing)', 'Nondevisa', 'Tolaram Group'),
('061', 'Bank ANZ Indonesia', 1990, 'Konvensional', 'Swasta (asing)', 'Devisa', 'ANZ'),
('037', 'Bank Artha Graha Internasional', 1973, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Artha Graha Network'),
('137', 'Bank Banten', 1992, 'Konvensional', 'BPD', 'Nondevisa', 'Pemerintah daerah di Banten'),
('536', 'Bank BCA Syariah', 1991, 'Syariah', 'Swasta (lokal)', 'Devisa', 'Bank Central Asia'),
('133', 'Bank Bengkulu', 1969, 'Konvensional', 'BPD', 'Nondevisa', 'Pemerintah daerah di Bengkulu'),
('110', 'Bank BJB', 1961, 'Konvensional', 'BPD', 'Devisa', 'Pemerintah daerah di Jawa Barat'),
('425', 'Bank BJB Syariah', 2010, 'Syariah', 'Swasta (lokal)', 'Nondevisa', 'Bank BJB'),
('057', 'Bank BNP Paribas Indonesia', 1989, 'Konvensional', 'Swasta (asing)', 'Devisa', 'BNP Paribas'),
('129', 'Bank BPD Bali', 1962, 'Konvensional', 'BPD', 'Devisa', 'Pemerintah daerah di Bali'),
('112', 'Bank BPD DIY', 1961, 'Konvensional', 'BPD', 'Nondevisa', 'Pemerintah daerah di Daerah Istimewa Yogyakarta'),
('119', 'Bank BRK Syariah', 1961, 'Syariah', 'BPD', 'Devisa', 'Pemerintah daerah di Riau dan Kepulauan Riau'),
('127', 'Bank BSG', 1961, 'Konvensional', 'BPD', 'Nondevisa', 'Pemerintah daerah di Sulawesi Utara dan Gorontalo'),
('547', 'Bank BTPN Syariah', 1991, 'Syariah', 'Swasta (asing)', 'Nondevisa', 'Bank SMBC Indonesia'),
('076', 'Bank Bumi Arta', 1967, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'PT Suryahusada Investment, Ajaib'),
('054', 'Bank Capital Indonesia', 1989, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Capital Financial Indonesia'),
('014', 'Bank Central Asia', 1955, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Djarum Group'),
('036', 'Bank CCB Indonesia', 1974, 'Konvensional', 'Swasta (asing)', 'Devisa', 'China Construction Bank'),
('022', 'Bank CIMB Niaga', 1955, 'Konvensional', 'Swasta (asing)', 'Devisa', 'CIMB Group'),
('949', 'Bank CTBC Indonesia', 1995, 'Konvensional', 'Swasta (asing)', 'Devisa', 'CTBC Financial Holding'),
('011', 'Bank Danamon Indonesia', 1956, 'Konvensional', 'Swasta (asing)', 'Devisa', 'MUFG'),
('046', 'Bank DBS Indonesia', 1989, 'Konvensional', 'Swasta (asing)', 'Devisa', 'DBS Bank'),
('501', 'Bank Digital BCA', 1965, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Bank Central Asia'),
('161', 'Bank Ganesha', 1990, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Equity Development Investment'),
('484', 'Bank Hana Indonesia', 1971, 'Konvensional', 'Swasta (asing)', 'Devisa', 'Hana Financial Group'),
('553', 'Bank Hibank Indonesia', 1993, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Bank Negara Indonesia'),
('087', 'Bank HSBC Indonesia', 1989, 'Konvensional', 'Swasta (asing)', 'Devisa', 'HSBC'),
('945', 'Bank IBK Indonesia', 1973, 'Konvensional', 'Swasta (asing)', 'Devisa', 'Industrial Bank of Korea'),
('164', 'Bank ICBC Indonesia', 1970, 'Konvensional', 'Swasta (asing)', 'Devisa', 'ICBC'),
('513', 'Bank Ina Perdana', 1990, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Salim Group'),
('555', 'Bank Index Selindo', 1992, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'PT Kazanah Indexindo'),
('542', 'Bank Jago', 1992, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Jerry Ng, GoTo Financial, dan Northstar Group'),
('111', 'Bank Jakarta', 1961, 'Konvensional', 'BPD', 'Devisa', 'Pemerintah daerah di Daerah Khusus Ibukota Jakarta'),
('115', 'Bank Jambi', 1959, 'Konvensional', 'BPD', 'Nondevisa', 'Pemerintah daerah di Jambi'),
('113', 'Bank Jateng', 1963, 'Konvensional', 'BPD', 'Devisa', 'Pemerintah daerah di Jawa Tengah'),
('114', 'Bank Jatim', 1961, 'Konvensional', 'BPD', 'Devisa', 'Pemerintah daerah di Jawa Timur'),
('095', 'Bank J Trust Indonesia', 1989, 'Konvensional', 'Swasta (asing)', 'Devisa', 'J Trust'),
('123', 'Bank Kalbar', 1963, 'Konvensional', 'BPD', 'Nondevisa', 'Pemerintah daerah di Kalimantan Barat'),
('122', 'Bank Kalsel', 1964, 'Konvensional', 'BPD', 'Devisa', 'Pemerintah daerah di Kalimantan Selatan'),
('125', 'Bank Kalteng', 1961, 'Konvensional', 'BPD', 'Nondevisa', 'Pemerintah daerah di Kalimantan Tengah'),
('124', 'Bank Kaltimtara', 1965, 'Konvensional', 'BPD', 'Devisa', 'Pemerintah daerah di Kalimantan Timur dan Utara'),
('441', 'Bank KB Indonesia', 1970, 'Konvensional', 'Swasta (asing)', 'Devisa', 'KB Financial Group'),
('521', 'Bank KB Syariah', 1990, 'Syariah', 'Swasta (asing)', 'Nondevisa', 'Bank KB Indonesia'),
('459', 'Bank Krom Indonesia', 1957, 'Konvensional', 'Swasta (asing)', 'Nondevisa', 'Kredivo Group'),
('121', 'Bank Lampung', 1964, 'Konvensional', 'BPD', 'Nondevisa', 'Pemerintah daerah di Lampung'),
('131', 'Bank Maluku Malut', 1961, 'Konvensional', 'BPD', 'Nondevisa', 'Pemerintah daerah di Maluku dan Maluku Utara'),
('008', 'Bank Mandiri', 1998, 'Konvensional', 'BUMN', 'Devisa', 'Pemerintah Republik Indonesia'),
('564', 'Bank Mandiri Taspen', 1970, 'Konvensional', 'Swasta (lokal)', 'Nondevisa', 'Bank Mandiri, Taspen'),
('157', 'Bank Maspion', 1989, 'Konvensional', 'Swasta (asing)', 'Devisa', 'Kasikornbank'),
('097', 'Bank Mayapada Internasional', 1989, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Mayapada Group'),
('016', 'Bank Maybank Indonesia', 1959, 'Konvensional', 'Swasta (asing)', 'Devisa', 'Maybank'),
('426', 'Bank Mega', 1969, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Mega Corpora'),
('506', 'Bank Mega Syariah', 1990, 'Syariah', 'Swasta (lokal)', 'Devisa', 'Mega Corpora'),
('151', 'Bank Mestika Dharma', 1955, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'PT Mestika Buana Mas'),
('048', 'Bank Mizuho Indonesia', 1989, 'Konvensional', 'Swasta (asing)', 'Devisa', 'Mizuho Financial Group'),
('485', 'Bank MNC Internasional', 1989, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'MNC Financial Services'),
('147', 'Bank Muamalat Indonesia', 1991, 'Syariah', 'Swasta (lokal)', 'Devisa', 'Badan Pengelola Keuangan Haji'),
('548', 'Bank Multiarta Sentosa', 1992, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Wings Group'),
('118', 'Bank Nagari', 1962, 'Konvensional', 'BPD', 'Devisa', 'Pemerintah daerah di Sumatera Barat'),
('253', 'Bank Nano Syariah', 2022, 'Syariah', 'Swasta (lokal)', 'Devisa', 'Bank Sinarmas'),
('503', 'Bank Nationalnobu', 1990, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Lippo Group dan Hanhwa Life Insurance'),
('009', 'Bank Negara Indonesia', 1946, 'Konvensional', 'BUMN', 'Devisa', 'Pemerintah Republik Indonesia'),
('490', 'Bank Neo Commerce', 1989, 'Konvensional', 'Swasta (lokal)', 'Nondevisa', 'Akulaku'),
('128', 'Bank NTB Syariah', 1964, 'Syariah', 'BPD', 'Nondevisa', 'Pemerintah daerah di Nusa Tenggara Barat'),
('130', 'Bank NTT', 1962, 'Konvensional', 'BPD', 'Devisa', 'Pemerintah daerah di Nusa Tenggara Timur'),
('028', 'Bank OCBC Indonesia', 1941, 'Konvensional', 'Swasta (asing)', 'Devisa', 'OCBC Bank'),
('146', 'Bank of India Indonesia', 1968, 'Konvensional', 'Swasta (asing)', 'Devisa', 'Bank of India'),
('526', 'Bank Oke Indonesia', 1990, 'Konvensional', 'Swasta (asing)', 'Nondevisa', 'Rush & Cash'),
('019', 'Bank Panin', 1971, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Panin Financial'),
('517', 'Bank Panin Dubai Syariah', 1972, 'Syariah', 'Swasta (lokal)', 'Devisa', 'Panin Bank, Dubai Islamic Bank'),
('132', 'Bank Papua', 1966, 'Konvensional', 'BPD', 'Nondevisa', 'Pemerintah daerah di Papua dan Papua Barat'),
('013', 'Bank Permata', 1954, 'Konvensional', 'Swasta (asing)', 'Devisa', 'Bangkok Bank'),
('167', 'Bank QNB Indonesia', 1913, 'Konvensional', 'Swasta (asing)', 'Devisa', 'QNB Group'),
('002', 'Bank Rakyat Indonesia', 1968, 'Konvensional', 'BUMN', 'Devisa', 'Pemerintah Republik Indonesia'),
('494', 'Bank Raya Indonesia', 1989, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Bank Rakyat Indonesia'),
('047', 'Bank Resona Perdania', 1956, 'Konvensional', 'Swasta (asing)', 'Devisa', 'Resona Holdings'),
('523', 'Bank Sahabat Sampoerna', 1990, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Sampoerna Strategic Group dan Xendit'),
('472', 'Bank Saqu Indonesia', 1971, 'Konvensional', 'Swasta (asing)', 'Nondevisa', 'WeLab, Astra International'),
('498', 'Bank SBI Indonesia', 1970, 'Konvensional', 'Swasta (asing)', 'Devisa', 'State Bank of India'),
('535', 'Bank Seabank Indonesia', 1991, 'Konvensional', 'Swasta (asing)', 'Nondevisa', 'Sea Limited'),
('152', 'Bank Shinhan Indonesia', 1967, 'Konvensional', 'Swasta (asing)', 'Devisa', 'Shinhan Financial Group'),
('153', 'Bank Sinarmas', 1989, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Sinar Mas Multiartha'),
('213', 'Bank SMBC Indonesia', 1958, 'Konvensional', 'Swasta (asing)', 'Devisa', 'SMBC Group'),
('126', 'Bank Sulselbar', 1961, 'Konvensional', 'BPD', 'Devisa', 'Pemerintah daerah di Sulawesi Selatan dan Barat'),
('134', 'Bank Sulteng', 1969, 'Konvensional', 'BPD', 'Nondevisa', 'Pemerintah daerah di Sulawesi Tengah'),
('135', 'Bank Sultra', 1968, 'Konvensional', 'BPD', 'Nondevisa', 'Pemerintah daerah di Sulawesi Tenggara'),
('120', 'Bank Sumsel Babel', 1957, 'Konvensional', 'BPD', 'Devisa', 'Pemerintah daerah di Sumatera Selatan dan Bangka Belitung'),
('117', 'Bank Sumut', 1961, 'Konvensional', 'BPD', 'Devisa', 'Pemerintah daerah di Sumatera Utara'),
('562', 'Bank Superbank Indonesia', 1993, 'Konvensional', 'Swasta (lokal)', 'Nondevisa', 'Elang Mahkota Teknologi dan Grab'),
('451', 'Bank Syariah Indonesia', 1969, 'Syariah', 'Swasta (lokal)', 'Devisa', 'Bank Mandiri, BRI, dan BNI'),
('405', 'Bank Syariah Nasional', 1966, 'Syariah', 'Swasta (lokal)', 'Nondevisa', 'Bank Tabungan Negara'),
('200', 'Bank Tabungan Negara', 1950, 'Konvensional', 'BUMN', 'Devisa', 'Pemerintah Republik Indonesia'),
('023', 'Bank UOB Indonesia', 1956, 'Konvensional', 'Swasta (asing)', 'Devisa', 'United Overseas Bank'),
('566', 'Bank Victoria Internasional', 1992, 'Konvensional', 'Swasta (lokal)', 'Devisa', 'Victoria Investama'),
('212', 'Bank Woori Saudara', 1974, 'Konvensional', 'Swasta (asing)', 'Devisa', 'Woori Bank');
